"""organization.memberships

Revision ID: 14fb6e01812b
Revises: 3fae7734210a
Create Date: 2012-09-03 18:54:25.215602

"""

# revision identifiers, used by Alembic.
revision = '14fb6e01812b'
down_revision = '3fae7734210a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text
from sqlalchemy.sql import functions as sqlf

Identifier = sa.BigInteger


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'Membership', sa.Column('organization_id', 
        Identifier(), 
        sa.ForeignKey('Organization.id', name="Membership_ibfk_1"),
        nullable=True))
    op.execute("""update Membership, Organization 
set Membership.organization_id = Organization.id 
where Organization.code = '89' 
and Membership.name = '89ers';
""")
    
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'Membership_ibfk_1', 'Membership', type="foreignkey")
    op.drop_column(u'Membership', 'organization_id')
    ### end Alembic commands ###
