"""membergroup

Revision ID: 19ead4ed557
Revises: 21b64604e7cf
Create Date: 2012-08-19 13:40:02.805278

"""

# revision identifiers, used by Alembic.
revision = '19ead4ed557'
down_revision = '9ef25d188e3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text
from sqlalchemy.sql import functions as sqlf
from sqlalchemy.dialects import mysql

Identifier = sa.BigInteger


def upgrade():
    ## commands auto generated by Alembic - please adjust! ###
    op.create_table('MemberGroup',
    sa.Column('id', Identifier(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('membership_id', Identifier(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sqlf.current_timestamp(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=text('0'), nullable=False),
    sa.ForeignKeyConstraint(['membership_id'], ['Membership.id'], name="MemberGroup_ibfk_1"),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table(u'Membership_SalesSegment')
    op.add_column(u'SalesSegment', sa.Column('membergroup_id', Identifier(), 
        sa.ForeignKey('MemberGroup.id', name='SalesSegment_ibfk_2'),
        nullable=True,
        ))
    op.add_column(u'User', sa.Column('membergroup_id', Identifier(),
        sa.ForeignKey('MemberGroup.id', name='User_ibfk_3'),
        nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Membership_SalesSegment',
         sa.Column('membership_id', Identifier(), nullable=False),
         sa.Column('sales_segment_id', Identifier(), nullable=False),
         sa.PrimaryKeyConstraint('membership_id', 'sales_segment_id'),
         sa.ForeignKeyConstraint(['membership_id'], ['Membership.id'], 'Membership_SalesSegment_ibfk_1'),
         sa.ForeignKeyConstraint(['sales_segment_id'], ['SalesSegment.id'], 'Membership_SalesSegment_ibfk_2')
         )
    op.drop_constraint('SalesSegment_ibfk_2', 'SalesSegment', type='foreignkey')
    op.drop_column('SalesSegment', 'membergroup_id')
    op.drop_constraint('User_ibfk_3', 'User', type='foreignkey')
    op.drop_column('User', 'membergroup_id')
    op.drop_table('MemberGroup')
    ### end Alembic commands ###
