"""LotRejectedEntry

Revision ID: 2673bcbc0dca
Revises: 5650beee2da
Create Date: 2012-12-12 00:23:16.269345

"""

# revision identifiers, used by Alembic.
revision = '2673bcbc0dca'
down_revision = '5650beee2da'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text
from sqlalchemy.sql import functions as sqlf

Identifier = sa.BigInteger
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LotRejectedEntry',
    sa.Column('id', Identifier(), nullable=False),
    sa.Column('lot_entry_id', Identifier(), nullable=True),
    sa.Column('mail_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=text('0'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['lot_entry_id'], ['LotEntry.id'], name="LotRejectedEntry_ibfk_1"),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('LotRejectedEntry')
    ### end Alembic commands ###
