"""MulticheckoutOrderStatus

Revision ID: 361d16266847
Revises: 51e772b5532c
Create Date: 2013-02-07 00:06:31.212944

"""

# revision identifiers, used by Alembic.
revision = '361d16266847'
down_revision = '51e772b5532c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text
from sqlalchemy.sql import functions as sqlf

Identifier = sa.BigInteger
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('multicheckout_order_status',
    sa.Column('id', Identifier(), nullable=False),
    sa.Column('OrderNo', sa.Unicode(length=32), nullable=True),
    sa.Column('Storecd', sa.Unicode(length=32), nullable=True),
    sa.Column('Status', sa.Unicode(length=3), nullable=True),
    sa.Column('Summary', sa.UnicodeText(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False,
                                server_default=sqlf.current_timestamp()),
    sa.Column('updated_at', sa.TIMESTAMP, nullable=False,
                               server_default=text('0'),
                               server_onupdate=sqlf.current_timestamp()),

    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('multicheckout_order_status')
    ### end Alembic commands ###
