"""Lot.description

Revision ID: 388e34a2537a
Revises: 1782323b168c
Create Date: 2012-12-04 17:28:03.071237

"""

# revision identifiers, used by Alembic.
revision = '388e34a2537a'
down_revision = '1782323b168c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text
from sqlalchemy.sql import functions as sqlf

Identifier = sa.BigInteger
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'Lot', sa.Column('description', sa.UnicodeText(), nullable=True))
    op.add_column(u'Lot', sa.Column('entry_limit', sa.Integer(), server_default="0", nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'Lot', 'entry_limit')
    op.drop_column(u'Lot', 'description')
    ### end Alembic commands ###
