"""MemberGroup_SalesSegment

Revision ID: 406252f94050
Revises: 9ef25d188e3
Create Date: 2012-08-22 03:54:25.550205

"""

# revision identifiers, used by Alembic.
revision = '406252f94050'
down_revision = '9ef25d188e3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text
from sqlalchemy.sql import functions as sqlf
from sqlalchemy.dialects import mysql

Identifier = sa.BigInteger

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MemberGroup_SalesSegment',
    sa.Column('id', Identifier(), nullable=False),
    sa.Column('membergroup_id', Identifier(), nullable=True),
    sa.Column('sales_segment_id', Identifier(), nullable=True),
    sa.ForeignKeyConstraint(['membergroup_id'], ['MemberGroup.id'], name="MemberGroup_SalesSegment_ibfk_1"),
    sa.ForeignKeyConstraint(['sales_segment_id'], ['SalesSegment.id'], name="MemberGroup_SalesSegment_ibfk_2" ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membergroup_id','sales_segment_id')
    )
    op.drop_constraint('SalesSegment_ibfk_2', 'SalesSegment', type='foreignkey')
    op.drop_column(u'SalesSegment', u'membergroup_id')
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'SalesSegment', sa.Column('membergroup_id', Identifier(), 
        sa.ForeignKey('MemberGroup.id', name='SalesSegment_ibfk_2'),
        nullable=True,
        ))
    op.drop_table('MemberGroup_SalesSegment')
    ### end Alembic commands ###
