"""guest login

Revision ID: 408a36838f2e
Revises: 10ed91837586
Create Date: 2012-08-26 20:19:38.744739

"""

# revision identifiers, used by Alembic.
revision = '408a36838f2e'
down_revision = '10ed91837586'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'MemberGroup', sa.Column('is_guest', sa.Boolean(), server_default='0', nullable=False))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'MemberGroup', 'is_guest')
    ### end Alembic commands ###
