"""multitenant

Revision ID: 423bbf5b2949
Revises: 4d71f19c4087
Create Date: 2012-09-19 16:44:55.019302

"""

# revision identifiers, used by Alembic.
revision = '423bbf5b2949'
#down_revision = '4d71f19c4087'
down_revision = "49fe03fd8e61"

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text
from sqlalchemy.sql import functions as sqlf, table, column

Identifier = sa.BigInteger
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Host',
    sa.Column('id', Identifier(), nullable=False),
    sa.Column('host_name', sa.Unicode(length=255), nullable=True),
    sa.Column('organization_id', Identifier(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=None, nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['Organization.id'], name="Host_ibfk_1"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('host_name')
    )

    op.create_table('MulticheckoutSetting',
    sa.Column('id', Identifier(), primary_key=True, nullable=False),
    sa.Column('shop_name', sa.Unicode(length=255), nullable=True),
    sa.Column('shop_id', sa.Unicode(length=255), nullable=True),
    sa.Column('auth_id', sa.Unicode(length=255), nullable=True),
    sa.Column('auth_password', sa.Unicode(length=255), nullable=True),
    sa.Column('organization_id', Identifier(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['Organization.id'], name="MulticheckoutSetting_ibfk_1"),
    sa.UniqueConstraint('shop_name')
    )

    
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Host_ibfk_1', 'Host', type="foreignkey")
    op.drop_table('Host')
    op.drop_constraint('MulticheckoutSetting_ibfk_1', 'MulticheckoutSetting', type="foreignkey")
    op.drop_table('MulticheckoutSetting')
    ### end Alembic commands ###
