"""Lot.lotting_announce

Revision ID: 429ba0125909
Revises: 2b6ce2f90991
Create Date: 2012-12-16 21:33:29.988596

"""

# revision identifiers, used by Alembic.
revision = '429ba0125909'
down_revision = '2b6ce2f90991'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text
from sqlalchemy.sql import functions as sqlf

Identifier = sa.BigInteger
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'Lot', sa.Column('lotting_announce_datetime', sa.DateTime(), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'Lot', 'lotting_announce_datetime')
    ### end Alembic commands ###
