"""cart.sales_segment

Revision ID: 5449082bc305
Revises: 2878cafe175e
Create Date: 2012-10-17 22:49:56.899387

"""

# revision identifiers, used by Alembic.
revision = '5449082bc305'
down_revision = '2878cafe175e'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text
from sqlalchemy.sql import functions as sqlf

Identifier = sa.BigInteger
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'ticketing_carts', 
        sa.Column('sales_segment_id', Identifier(), sa.ForeignKey('SalesSegment.id', name=u'ticketing_carts_ibfk_5'),
        nullable=True,)
        )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'ticketing_carts_ibfk_5', u'ticketing_carts', type="foreignkey")
    op.drop_column(u'ticketing_carts', 'sales_segment_id')
    ### end Alembic commands ###
