"""cart.order

Revision ID: 586c92fc1931
Revises: a2b7618aece
Create Date: 2012-09-05 17:56:14.484920

"""

# revision identifiers, used by Alembic.
revision = '586c92fc1931'
down_revision = '2118ba6ee220'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text
from sqlalchemy.sql import functions as sqlf

Identifier = sa.BigInteger
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'ticketing_carts', sa.Column('order_id', 
        Identifier(), 
        sa.ForeignKey('Order.id', name="ticketing_carts_ibfk_4"),
        nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ticketing_carts_ibfk_4', 'ticketing_carts', type='foreignkey')
    op.drop_column(u'ticketing_carts', 'order_id')
    ### end Alembic commands ###
