"""carts,lots organization_id

Revision ID: 6ee82086f5a
Revises: 20b9eeb7686
Create Date: 2013-07-12 12:08:34.890562

"""

# revision identifiers, used by Alembic.
revision = '6ee82086f5a'
down_revision = '20b9eeb7686'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text
from sqlalchemy.sql import functions as sqlf

Identifier = sa.BigInteger
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Cart',
                  sa.Column('organization_id', Identifier(), sa.ForeignKey('Organization.id', name='Cart_ibfk_8'), nullable=True))
    op.add_column('CartedProduct',
                  sa.Column('organization_id', Identifier(), sa.ForeignKey('Organization.id', name="CartedProduct_ibfk_3"), nullable=True))
    op.add_column('CartedProductItem',
                  sa.Column('organization_id', Identifier(), sa.ForeignKey('Organization.id', name="CartedProductItem_ibfk_3"), nullable=True))
    op.add_column('Lot',
                  sa.Column('organization_id', Identifier(), sa.ForeignKey('Organization.id', name="Lot_ibfk_4"), nullable=True))
    op.add_column('LotEntry',
                  sa.Column('organization_id', Identifier(), sa.ForeignKey('Organization.id', name="LotEntry_ibfk_8"), nullable=True))
    op.add_column('LotEntryProduct',
                  sa.Column('organization_id', Identifier(), sa.ForeignKey('Organization.id', name="LotEntryProduct_ibfk_4"), nullable=True))
    op.add_column('LotEntryWish',
                  sa.Column('organization_id', Identifier(), sa.ForeignKey('Organization.id', name="LotEntryWish_ibfk_4"), nullable=True))
    op.add_column('LotWorkHistory',
                  sa.Column('organization_id', Identifier(), sa.ForeignKey('Organization.id', name="LotWorkHistory_ibfk_2"), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('LotWorkHistory_ibfk_2', 'LotWorkHistory', type="foreignkey")
    op.drop_column('LotWorkHistory', 'organization_id')

    op.drop_constraint('LotEntryWish_ibfk_4', 'LotEntryWish', type="foreignkey")
    op.drop_column('LotEntryWish', 'organization_id')

    op.drop_constraint('LotEntryProduct_ibfk_4', 'LotEntryProduct', type="foreignkey")
    op.drop_column('LotEntryProduct', 'organization_id')

    op.drop_constraint('LotEntry_ibfk_8', 'LotEntry', type="foreignkey")
    op.drop_column('LotEntry', 'organization_id')

    op.drop_constraint('Lot_ibfk_4', 'Lot', type="foreignkey")
    op.drop_column('Lot', 'organization_id')

    op.drop_constraint('CartedProductItem_ibfk_3', 'CartedProductItem', type="foreignkey")
    op.drop_column('CartedProductItem', 'organization_id')

    op.drop_constraint('CartedProduct_ibfk_3', 'CartedProduct', type="foreignkey")
    op.drop_column('CartedProduct', 'organization_id')

    op.drop_constraint('Cart_ibfk_8', 'Cart', type="foreignkey")
    op.drop_column('Cart', 'organization_id')
    ### end Alembic commands ###
