"""create queue entry datum

Revision ID: 7155803f136
Revises: 136af24cc0c
Create Date: 2013-01-08 18:42:00.842766

"""

# revision identifiers, used by Alembic.
revision = '7155803f136'
down_revision = '136af24cc0c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text
from sqlalchemy.sql import functions as sqlf

Identifier = sa.BigInteger
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TicketPrintQueueEntryDatum',
    sa.Column('queue_entry_id', Identifier(), nullable=False),
    sa.Column('data', sa.String(length=65536), nullable=False, default=''),
    sa.ForeignKeyConstraint(['queue_entry_id'], ['TicketPrintQueueEntry.id'], ),
    sa.PrimaryKeyConstraint('queue_entry_id')
    )

def downgrade():
    op.drop_table('TicketPrintQueueEntryDatum')
