"""Host.base_url

Revision ID: b43ac6db823
Revises: 54d62937d132
Create Date: 2012-11-27 23:25:03.278883

"""

# revision identifiers, used by Alembic.
revision = 'b43ac6db823'
down_revision = '54d62937d132'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql.expression import text
from sqlalchemy.sql import functions as sqlf

Identifier = sa.BigInteger
from sqlalchemy.dialects import mysql

def upgrade():
    op.add_column(u'Host', sa.Column('base_url', sa.Unicode(length=255), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'Host', 'base_url')
    ### end Alembic commands ###
