# -*- coding:utf-8 -*-
"""create tickethub models

Revision ID: e70924e0642
Revises: 44b46209e07f
Create Date: 2019-11-29 00:38:26.493635

"""

# revision identifiers, used by Alembic.
revision = 'e70924e0642'
down_revision = '44b46209e07f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import functions as sqlf
from sqlalchemy.sql.expression import text

Identifier = sa.BigInteger

from altair.app.ticketing.payments.plugins import TICKET_HUB_DELIVERY_PLUGIN_ID

def upgrade():
    op.execute(u"INSERT INTO DeliveryMethodPlugin (id, name) VALUES({0}, 'GOOD_FELLOWS_QRゲート');"
               .format(TICKET_HUB_DELIVERY_PLUGIN_ID))
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TicketHubFacility',
        sa.Column('id', Identifier(), nullable=False),
        sa.Column('code', sa.String(length=5), nullable=True),
        sa.Column('agent_code', sa.String(length=4), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=text('0'), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sqlf.current_timestamp(), nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.create_index('ix_TicketHubFacility_deleted_at', 'TicketHubFacility', ['deleted_at'], unique=False)
    op.create_table('TicketHubItemGroup',
        sa.Column('id', Identifier(), nullable=False),
        sa.Column('code', sa.String(length=4), nullable=True),
        sa.Column('ticket_hub_facility_id', Identifier(), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=text('0'), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sqlf.current_timestamp(), nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['ticket_hub_facility_id'], ['TicketHubFacility.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.create_index('ix_TicketHubItemGroup_deleted_at', 'TicketHubItemGroup', ['deleted_at'], unique=False)
    op.create_table('TicketHubItem',
        sa.Column('id', Identifier(), nullable=False),
        sa.Column('code', sa.String(length=5), nullable=True),
        sa.Column('ticket_hub_item_group_id', Identifier(), nullable=False),
        sa.Column('product_id', Identifier(), nullable=False),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=text('0'), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sqlf.current_timestamp(), nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['product_id'], ['Product.id'], ),
        sa.ForeignKeyConstraint(['ticket_hub_item_group_id'], ['TicketHubItemGroup.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('code')
    )
    op.create_index('ix_TicketHubItem_deleted_at', 'TicketHubItem', ['deleted_at'], unique=False)
    op.create_table('TicketHubOrder',
        sa.Column('id', Identifier(), nullable=False),
        sa.Column('order_id', Identifier(), nullable=False),
        sa.Column('altair_order_no', sa.Unicode(255), nullable=False),
        sa.Column('cart_no', sa.String(length=36), nullable=False),
        sa.Column('order_no', sa.String(length=20), nullable=False),
        sa.Column('purchase_no', sa.String(length=30), nullable=False),
        sa.Column('purchase_qr_code', sa.String(length=41), nullable=False),
        sa.Column('total_amount', sa.String(length=8), nullable=False),
        sa.Column('total_ticket_quantity', sa.String(length=8), nullable=False),
        sa.Column('requested_at', sa.DateTime(), nullable=False),
        sa.Column('canceled_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=text('0'), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sqlf.current_timestamp(), nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['order_id'], ['Order.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('order_no')
    )
    op.create_index('ix_TicketHubOrder_deleted_at', 'TicketHubOrder', ['deleted_at'], unique=False)
    op.create_table('TicketHubOrderedTicket',
        sa.Column('id', Identifier(), nullable=False),
        sa.Column('ticket_hub_order_id', Identifier(), nullable=False),
        sa.Column('qr_code', sa.String(length=41), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), server_default=text('0'), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), server_default=sqlf.current_timestamp(), nullable=False),
        sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['ticket_hub_order_id'], ['TicketHubOrder.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_TicketHubOrderedTicket_deleted_at', 'TicketHubOrderedTicket', ['deleted_at'], unique=False)
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_TicketHubOrderedTicket_deleted_at', table_name='TicketHubOrderedTicket')
    op.drop_table('TicketHubOrderedTicket')
    op.drop_index('ix_TicketHubOrder_deleted_at', table_name='TicketHubOrder')
    op.drop_table('TicketHubOrder')
    op.drop_index('ix_TicketHubItem_deleted_at', table_name='TicketHubItem')
    op.drop_table('TicketHubItem')
    op.drop_index('ix_TicketHubItemGroup_deleted_at', table_name='TicketHubItemGroup')
    op.drop_table('TicketHubItemGroup')
    op.drop_index('ix_TicketHubFacility_deleted_at', table_name='TicketHubFacility')
    op.drop_table('TicketHubFacility')
    ### end Alembic commands ###
    op.execute(u"DELETE FROM DeliveryMethodPlugin WHERE id={0};".format(TICKET_HUB_DELIVERY_PLUGIN_ID))
