"""add linklist limit_span

Revision ID: 28e9b6af38df
Revises: 49442bfedb1c
Create Date: 2012-06-14 19:28:56.453601

"""

# revision identifiers, used by Alembic.
revision = '28e9b6af38df'
down_revision = '49442bfedb1c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('widget_linklist', sa.Column('limit_span', sa.Integer(), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('widget_linklist', 'limit_span')
    ### end Alembic commands ###
