""" operator has many roles.

Revision ID: 30951fbe98bc
Revises: 1ba3266beb3
Create Date: 2012-05-28 17:07:53.316132

"""

# revision identifiers, used by Alembic.
revision = '30951fbe98bc'
down_revision = '1ba3266beb3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_role',
    sa.Column('operator_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint()
    )
    op.execute("ALTER TABLE operator DROP FOREIGN KEY operator_ibfk_2")
    op.drop_column('operator', u'role_id')
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('operator', sa.Column(u'role_id', mysql.INTEGER(display_width=11), nullable=True))
    op.drop_table('operator_role')
    ### end Alembic commands ###
