"""empty message

Revision ID: 3547c611528b
Revises: 39310a55951f
Create Date: 2012-05-31 11:21:07.282303

"""

# revision identifiers, used by Alembic.
revision = '3547c611528b'
down_revision = '39310a55951f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_role',
                    sa.Column('operator_id', sa.Integer(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
                    sa.PrimaryKeyConstraint()
                    )

def downgrade():
    op.drop_table("operator_role")

