"""version

Revision ID: 35b4197519e7
Revises: 53efa70a2dca
Create Date: 2012-04-18 09:26:32.131754

"""

# revision identifiers, used by Alembic.
revision = '35b4197519e7'
down_revision = '53efa70a2dca'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagesets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'page', sa.Column('pageset_id', sa.Integer(), nullable=True))
    op.add_column(u'page', sa.Column('publish_begin', sa.DateTime(), nullable=True))
    op.add_column(u'page', sa.Column('publis_end', sa.DateTime(), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagesets')
    op.drop_column(u'page', 'pageset_id')
    op.drop_column(u'page', 'publish_begin')
    op.drop_column(u'page', 'publis_end')
    ### end Alembic commands ###
