"""empty message

Revision ID: 368ab65b72b1
Revises: 3f53c33dd49c
Create Date: 2012-05-06 20:17:40.712071

"""

# revision identifiers, used by Alembic.
revision = '368ab65b72b1'
down_revision = '3f53c33dd49c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('event_create', 'event_read', 'event_update', 'event_delete', 'topic_create', 'topic_read', 'topic_update', 'topic_delete', 'ticket_create', 'ticket_read', 'ticket_update', 'ticket_delete', 'magazine_create', 'magazine_read', 'magazine_update', 'magazine_delete', 'asset_create', 'asset_read', 'asset_update', 'asset_delete', 'page_create', 'page_read', 'page_update', 'page_delete', 'tag_create', 'tag_read', 'tag_update', 'tag_delete', 'layout_create', 'layout_read', 'layout_update', 'layout_delete', 'operator_create', 'operator_read', 'operator_update', 'operator_delete'), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('TODO'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table(u'role2permission')
    op.drop_table(u'permission')
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'permission',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'name', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'role2permission',
    sa.Column(u'id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column(u'role_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.Column(u'permission_id', mysql.INTEGER(display_width=11), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], [u'permission.id'], name=u'role2permission_ibfk_1'),
    sa.ForeignKeyConstraint(['role_id'], [u'role.id'], name=u'role2permission_ibfk_2'),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.drop_table('role_permissions')
    ### end Alembic commands ###
