"""pageset event

Revision ID: 41d8895fd52a
Revises: 49514ed6e655
Create Date: 2012-04-23 17:39:09.427272

"""

# revision identifiers, used by Alembic.
revision = '41d8895fd52a'
down_revision = '49514ed6e655'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagesets', sa.Column('event_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagesets', 'event_id')
    ### end Alembic commands ###
