"""version column

Revision ID: 47782a94abb6
Revises: 5632fad03927
Create Date: 2012-04-19 15:04:39.559612

"""

# revision identifiers, used by Alembic.
revision = '47782a94abb6'
down_revision = '5632fad03927'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagesets', sa.Column('version_counter', sa.Integer(), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagesets', 'version_counter')
    ### end Alembic commands ###
