"""publis_end -> publish_end

Revision ID: 49514ed6e655
Revises: 47782a94abb6
Create Date: 2012-04-20 13:06:47.572629

"""

# revision identifiers, used by Alembic.
revision = '49514ed6e655'
down_revision = '47782a94abb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page', u'publis_end', name=u'publish_end', existing_type=sa.DateTime)
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('page', u'publish_end', name=u'publis_end', existing_type=sa.DateTime)
    ### end Alembic commands ###
