"""first models

Revision ID: 5383f63a769e
Revises: None
Create Date: 2012-04-17 14:57:30.410163

"""

# revision identifiers, used by Alembic.
revision = '5383f63a769e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('prefecture', sa.Unicode(length=255), nullable=True),
    sa.Column('address', sa.Unicode(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('contract_status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('name', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('template_filename', sa.String(length=255), nullable=True),
    sa.Column('blocks', sa.String(length=255), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('subtitle', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('place', sa.Unicode(length=255), nullable=True),
    sa.Column('inquiry_for', sa.Unicode(length=255), nullable=True),
    sa.Column('event_open', sa.DateTime(), nullable=True),
    sa.Column('event_close', sa.DateTime(), nullable=True),
    sa.Column('deal_open', sa.DateTime(), nullable=True),
    sa.Column('deal_close', sa.DateTime(), nullable=True),
    sa.Column('is_searchable', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seatfigure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('figure_url', sa.String(length=255), nullable=True),
    sa.Column('controller_url', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assettag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Unicode(length=255), nullable=True),
    sa.Column('publicp', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.CheckConstraint('TODO'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_source', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('screen_name', sa.Unicode(length=255), nullable=True),
    sa.Column('oauth_token', sa.String(length=255), nullable=True),
    sa.Column('oauth_token_secret', sa.String(length=255), nullable=True),
    sa.Column('date_joined', sa.DateTime(), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_asset',
    sa.Column('alt', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(length=255), nullable=True),
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('backend_performance_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('venue', sa.Unicode(length=255), nullable=True),
    sa.Column('open_on', sa.DateTime(), nullable=True),
    sa.Column('start_on', sa.DateTime(), nullable=True),
    sa.Column('close_on', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_asset',
    sa.Column('alt', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(length=255), nullable=True),
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagepath', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flash_asset',
    sa.Column('alt', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(length=255), nullable=True),
    sa.Column('imagepath', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('is_administrator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailmagazine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailmagazine_distribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailmagazine_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.Unicode(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('send_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mailmagazine_id'], ['mailmagazine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailmagazine_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailmagazine_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('can_distribute', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mailmagazine_id'], ['mailmagazine.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assettag2asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['assettag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('apikey',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('apikey', sa.String(length=255), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role2permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('performance_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('start_on', sa.DateTime(), nullable=True),
    sa.Column('close_on', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['performance_id'], ['performance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_token',
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('keywords', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.Unicode(length=255), nullable=True),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('layout_id', sa.Integer(), nullable=True),
    sa.Column('structure', sa.String(length=255), nullable=True),
    sa.Column('hash_url', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['layout_id'], ['layout.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['page.id'], name='fk_page_parent_id'),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagetag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Unicode(length=255), nullable=True),
    sa.Column('publicp', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('TODO'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagetag2page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['pagetag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgetdisposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('structure', sa.String(length=255), nullable=True),
    sa.Column('blocks', sa.String(length=255), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('TODO'),
    sa.ForeignKeyConstraint(['owner_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget',
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('disposition_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disposition_id'], ['widgetdisposition.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_breadcrumbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('items', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_type', sa.String(length=255), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_countdown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_performancelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_flash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_ticketlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('items', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_type', sa.String(length=255), nullable=True),
    sa.Column('display_count', sa.Integer(), nullable=True),
    sa.Column('display_global', sa.Boolean(), nullable=True),
    sa.Column('display_event', sa.Boolean(), nullable=True),
    sa.Column('display_page', sa.Boolean(), nullable=True),
    sa.Column('kind', sa.Unicode(length=255), nullable=True),
    sa.CheckConstraint('TODO'),
    sa.CheckConstraint('TODO'),
    sa.CheckConstraint('TODO'),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_reuse',
    sa.Column('attrs', sa.String(length=255), nullable=True),
    sa.Column('source_page_id', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.ForeignKeyConstraint(['source_page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(length=255), nullable=True),
    sa.Column('alt', sa.Unicode(length=255), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('nowrap', sa.Boolean(), nullable=True),
    sa.CheckConstraint('TODO'),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('publish_open_on', sa.DateTime(), nullable=True),
    sa.Column('publish_close_on', sa.DateTime(), nullable=True),
    sa.Column('orderno', sa.Integer(), nullable=True),
    sa.Column('is_vetoed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Unicode(length=255), nullable=True),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('text', sa.Unicode(length=255), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.CheckConstraint('TODO'),
    sa.CheckConstraint('TODO'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ticket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderno', sa.Integer(), nullable=True),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('seattype', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['performance.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topcontent',
    sa.Column('publish_open_on', sa.DateTime(), nullable=True),
    sa.Column('publish_close_on', sa.DateTime(), nullable=True),
    sa.Column('orderno', sa.Integer(), nullable=True),
    sa.Column('is_vetoed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Unicode(length=255), nullable=True),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('text', sa.Unicode(length=255), nullable=True),
    sa.Column('image_asset_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('countdown_type', sa.String(length=255), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.CheckConstraint('TODO'),
    sa.CheckConstraint('TODO'),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['image_asset_id'], ['image_asset.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widget_summary')
    op.drop_table('widget_text')
    op.drop_table('widget_calendar')
    op.drop_table('topic')
    op.drop_table('ticket')
    op.drop_table('operator')
    op.drop_table('mailmagazine_distribute')
    op.drop_table('image_asset')
    op.drop_table('mailmagazine_user')
    op.drop_table('widget_breadcrumbs')
    op.drop_table('layout')
    op.drop_table('widget_movie')
    op.drop_table('mailmagazine')
    op.drop_table('seatfigure')
    op.drop_table('topcontent')
    op.drop_table('event')
    op.drop_table('assettag')
    op.drop_table('role')
    op.drop_table('asset')
    op.drop_table('order_history')
    op.drop_table('performance')
    op.drop_table('movie_asset')
    op.drop_table('widget')
    op.drop_table('widget_countdown')
    op.drop_table('permission')
    op.drop_table('flash_asset')
    op.drop_table('widget_performancelist')
    op.drop_table('widget_flash')
    op.drop_table('widget_ticketlist')
    op.drop_table('widget_menu')
    op.drop_table('pagetag')
    op.drop_table('user')
    op.drop_table('assettag2asset')
    op.drop_table('pagetag2page')
    op.drop_table('widget_topic')
    op.drop_table('widgetdisposition')
    op.drop_table('widget_reuse')
    op.drop_table('apikey')
    op.drop_table('widget_image')
    op.drop_table('role2permission')
    op.drop_table('sale')
    op.drop_table('client')
    op.drop_table('oauth_token')
    op.drop_table('page')
    op.drop_table('widget_detail')
    op.drop_table('site')
    ### end Alembic commands ###
