"""empty message

Revision ID: 5632fad03927
Revises: 35b4197519e7
Create Date: 2012-04-18 16:27:36.878740

"""

# revision identifiers, used by Alembic.
revision = '5632fad03927'
down_revision = '35b4197519e7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagesets', sa.Column('url', sa.String(length=255), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagesets', 'url')
    ### end Alembic commands ###
