"""add bound event in summary widget

Revision ID: 59c7192b3ca5
Revises: 2cd70c991fc4
Create Date: 2012-06-23 17:02:36.100465

"""

# revision identifiers, used by Alembic.
revision = '59c7192b3ca5'
down_revision = '2cd70c991fc4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance', u'backend_id', 
               existing_type=mysql.INTEGER(display_width=11), 
               nullable=True)
    op.add_column('widget_summary', sa.Column('bound_event_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('performance', u'backend_id', 
               existing_type=mysql.INTEGER(display_width=11), 
               nullable=False)
    op.drop_column('widget_summary', 'bound_event_id')
    ### end Alembic commands ###
