/* To be created on report DB. Data is to be written by select_sales_by_performance.py */

drop table if exists rt_sales2016;
create table rt_sales2016 (
    id int unsigned not null auto_increment,
    perf_id int unsigned not null,
    perf_name varchar(1023) not null,
    start_date date not null,
    end_date date default null,
    account_name varchar(255),
    event_id int unsigned not null,
    event_name varchar(1023) not null,
    total_sales int unsigned not null,
    ticket_count_sum int unsigned default null,
    order_count_sum int unsigned not null,
    order_count_creditcard int unsigned default null,
    order_count_sej_payment int unsigned default null,
    order_count_famiport_payment int unsigned default null,
    order_count_rakuten_payment int unsigned default null,
    order_count_reserve_payment int unsigned default null,
    order_count_shipping_delivery int unsigned default null,
    order_count_sej_delivery int unsigned default null,
    order_count_famiport_delivery int unsigned default null,
    order_count_reserve_delivery int unsigned default null,
    order_count_qr_delivery int unsigned default null,
    order_count_orion_delivery int unsigned default null,
    transaction_fee_sum int unsigned not null,
    transaction_fee_creditcard int unsigned default null,
    transaction_fee_sej int unsigned default null,
    transaction_fee_famiport int unsigned default null,
    transaction_fee_rakuten int unsigned default null,
    transaction_fee_reserve int unsigned default null,
    delivery_fee_sum int unsigned not null,
    delivery_fee_shipping int unsigned default null,
    delivery_fee_sej int unsigned default null,
    delivery_fee_famiport int unsigned default null,
    delivery_fee_reserve int unsigned default null,
    delivery_fee_qr int unsigned default null,
    delivery_fee_orion int unsigned default null,
    system_fee_sum int unsigned not null,
    special_fee_sum int unsigned not null,
    primary key (id),
    key (perf_id),
    key (event_id)
) engine=innodb default charset=utf8;