  <div class="footer">
	  
        <div class="footernav">
          <ul>
            <li class="first"><a href="${request.route_url('contact')}">お問い合わせ</a></li>
            <li><a href="http://privacy.rakuten.co.jp/">個人情報保護方針</a></li>
            <li class="last"><a href="http://www.ticketstar.jp/legal">特定商取引法に基づく表示</a></li>
          </ul>
        </div>
        <div class="copyright">
          Copyright &copy; 2010-2012 TicketStar Inc. All Rights Reserved. 
        </div>

  </div>
