//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("CheckinStation")]
[assembly: System.Reflection.AssemblyDescription("altair checkin station")]
[assembly: System.Reflection.AssemblyProduct("CheckinStation")]
[assembly: System.Reflection.AssemblyCopyright("Copyright @ 2014")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("0.0.0.08e27086a3559ebcd5c43bbae4f84ce6e0030ca7")]
[assembly: System.Reflection.AssemblyVersion("0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.0")]


