//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("CheckinStation")]
[assembly: System.Reflection.AssemblyDescription("altair checkin station")]
[assembly: System.Reflection.AssemblyProduct("CheckinStation")]
[assembly: System.Reflection.AssemblyCopyright("Copyright @ 2015")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.b7d7fa0b811afff2e4ca43ec053f6c208cd6e5bc")]
[assembly: System.Reflection.AssemblyVersion("1.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0")]


