//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("CheckinStation")]
[assembly: System.Reflection.AssemblyDescription("altair checkin station")]
[assembly: System.Reflection.AssemblyProduct("CheckinStation")]
[assembly: System.Reflection.AssemblyCopyright("Copyright @ 2014")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Reflection.AssemblyInformationalVersion("0.0.0.290c6eaf1033d994e10b6e00b1386d291c8f23c1")]
[assembly: System.Reflection.AssemblyVersion("0.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("0.0.0")]


