# package
def includeme(config):
    config.include('.company')
    config.include('.detailsearch')
    config.include('.eventdetail')
    config.include('.genre')
    config.include('.help')
    config.include('.hotword')
    config.include('.information')
    config.include('.search')
    config.include('.orderreview')
    config.include('.inquiry')
    config.include('.privacy')
    config.include('.legal')
    config.include('.maintenance')
