@startuml
Class Bank {
	id 		BigInteger
	code 		BigInteger
	name 		String
	+		addresses

}

Class BankAccount {
	id 		BigInteger
	back_id 		BigInteger
	account_type 		Integer
	account_number 		String
	account_owner 		String
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		bank
	+		client

}

Class Client {
	id 		BigInteger
	contract_type 		Integer
	event_ticket_owner_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		event_ticket_owner

}

Class Event {
	id 		BigInteger
	start_on 		Date
	end_on 		Date
	publish_at 		DateTime
	code 		String
	title 		String
	abbreviated_title 		String
	margin_ratio 		Float
	printing_fee 		Float
	registration_fee 		Float
	seats_and_prices 		String
	+		performances

}

Class EventTicketOwner {
	id 		BigInteger
	owner_type 		Integer
	bank_account_id 		BigInteger
	user_id 		BigInteger
	name 		String
	company_name 		String
	section_name 		String
	zip_code 		String
	country_code 		Integer
	prefecture_code 		Integer
	city 		String
	address 		String
	street 		String
	other_address 		String
	tel_1 		String
	tel_2 		String
	fax 		String
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		bank_account
	+		user
	+		client

}

Class EventTicketOwnerHistory {
	id 		BigInteger
	seat_masterl2_id 		BigInteger
	ticket_owner_id 		BigInteger
	src_ticket_owner_id 		BigInteger
	dst_ticket_owner_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		ticket_owner
	+		src_ticket_owner
	+		dst_ticket_owner
	+		seat_masterl2

}

Class MailPermission {
	id 		BigInteger
	email 		String
	user_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		user

}

Class Operator {
	id 		BigInteger
	name 		String
	email 		String
	client_id 		BigInteger
	expire_at 		DateTime
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	login_id 		String
	password 		String
	auth_code 		String
	access_token 		String
	secret_key 		String
	+		client
	+		roles

}

Class OperatorActionHistory {
	id 		BigInteger
	function 		String
	data 		String
	created_at 		DateTime
	operator_id 		BigInteger
	+		operator

}

Class OperatorRole {
	id 		BigInteger
	name 		String
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		operators
	+		permissions

}

Class Order {
	id 		BigInteger
	user_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		user
	+		items
	+		shipping_id

}

Class OrderItem {
	id 		BigInteger
	order_id 		BigInteger
	product_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		product
	+		product_items
	+		order

}

Class Performance {
	id 		BigInteger
	event_id 		BigInteger
	open_on 		DateTime
	start_on 		DateTime
	end_on 		DateTime
	no_period 		Boolean
	name 		String
	code 		String
	owner_id 		BigInteger
	+		owner
	+		event

}

Class Permission {
	id 		BigInteger
	operator_role_id 		BigInteger
	category_code 		Integer
	permit 		Integer
	+		operator_role

}

Class Product {
	id 		BigInteger
	name 		String
	price 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		items

}

Class ProductItem {
	id 		BigInteger
	product_item_master_id 		BigInteger
	order_item_id 		BigInteger
	seat_stock_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		product_item_master
	+		seat_stock
	+		order_item

}

Class ProductItemMaster {
	id 		BigInteger
	product_id 		BigInteger
	price 		BigInteger
	item_type 		Integer
	performance_id 		BigInteger
	ticket_type_id 		BigInteger
	seat_type_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		performance
	+		ticket_type
	+		seat_type
	+		product

}

Class SeatMasterL2 {
	id 		BigInteger
	performance_id 		BigInteger
	seat_type_id 		BigInteger
	group_id 		Integer
	ticket_owner_id 		BigInteger
	venue_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		performance
	+		seat_type
	+		ticket_owner
	+		ticket_owner_history
	+		seat_stock_id

}

Class SeatStock {
	id 		BigInteger
	seat_id 		Integer
	sold 		Boolean
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		seat

}

Class SeatType {
	id 		BigInteger
	name 		String
	event_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		event

}

Class ShippingAddress {
	id 		BigInteger
	user_id 		BigInteger
	order_id 		BigInteger
	nick_name 		String
	first_name 		String
	last_name 		String
	first_name_kana 		String
	last_name_kana 		String
	birth_day 		DateTime
	sex 		Integer
	zip 		String
	prefecture 		String
	city 		String
	street 		String
	address 		String
	other_address 		String
	tel_1 		String
	tel_2 		String
	fax 		String
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		user
	+		order

}

Class Stock {
	id 		BigInteger
	performance_id 		BigInteger
	seat_type_id 		BigInteger
	quantity 		Integer
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		performance
	+		seat_type

}

Class TicketType {
	id 		BigInteger
	name 		String
	event_id 		BigInteger
	price 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		event

}

Class User {
	id 		BigInteger
	open_id_identifier 		String
	email 		String
	nick_name 		String
	first_name 		String
	last_name 		String
	first_name_kana 		String
	last_name_kana 		String
	birth_day 		DateTime
	sex 		Integer
	zip 		String
	prefecture 		String
	city 		String
	street 		String
	address 		String
	other_address 		String
	tel_1 		String
	tel_2 		String
	fax 		String
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		point_accounts
	+		user_point

}

Class UserPointAccount {
	id 		BigInteger
	user_id 		BigInteger
	point_type_code 		Integer
	account_number 		String
	account_expire 		String
	account_owner 		String
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		user

}

Class UserPointHistory {
	id 		BigInteger
	user_point_account_id 		BigInteger
	point 		Integer
	rate 		Integer
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		user_point_account

}

Class Event_DETAIL {
	id 		BigInteger
	seats_and_prices 		String


}

Class Event {
	id 		BigInteger
	start_on 		Date
	end_on 		Date
	publish_at 		DateTime
	code 		String
	title 		String
	abbreviated_title 		String
	margin_ratio 		Float
	printing_fee 		Float
	registration_fee 		Float


}

Class Operator_Auth {
	id 		BigInteger
	login_id 		String
	password 		String
	auth_code 		String
	access_token 		String
	secret_key 		String


}

Class OperatorRole_Operator {
	operator_role_id 		BigInteger
	operator_id 		BigInteger


}

Class Operator {
	id 		BigInteger
	name 		String
	email 		String
	client_id 		BigInteger
	expire_at 		DateTime
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer


}

BankAccount <--o Bank: back_id

Client <--o EventTicketOwner: event_ticket_owner_id

EventTicketOwner <--o BankAccount: bank_account_id

EventTicketOwner <--o User: user_id

EventTicketOwnerHistory <--o SeatMasterL2: seat_masterl2_id

EventTicketOwnerHistory <--o EventTicketOwner: ticket_owner_id

EventTicketOwnerHistory <--o EventTicketOwner: src_ticket_owner_id

EventTicketOwnerHistory <--o EventTicketOwner: dst_ticket_owner_id

MailPermission <--o User: user_id

Operator <--o Client: client_id

OperatorActionHistory <--o Operator: operator_id

Order <--o User: user_id

OrderItem <--o Order: order_id

OrderItem <--o Product: product_id

Performance <--o Event: event_id

Performance <--o EventTicketOwner: owner_id

Permission <--o OperatorRole: operator_role_id

ProductItem <--o ProductItemMaster: product_item_master_id

ProductItem <--o OrderItem: order_item_id

ProductItem <--o SeatStock: seat_stock_id

ProductItemMaster <--o Product: product_id

ProductItemMaster <--o Performance: performance_id

ProductItemMaster <--o TicketType: ticket_type_id

ProductItemMaster <--o SeatType: seat_type_id

SeatMasterL2 <--o Performance: performance_id

SeatMasterL2 <--o SeatType: seat_type_id

SeatMasterL2 <--o EventTicketOwner: ticket_owner_id

SeatStock <--o SeatMasterL2: seat_id

SeatType <--o Event: event_id

ShippingAddress <--o User: user_id

ShippingAddress <--o Order: order_id

Stock <--o Performance: performance_id

Stock <--o SeatType: seat_type_id

TicketType <--o Event: event_id

UserPointAccount <--o User: user_id

UserPointHistory <--o UserPointAccount: user_point_account_id

OperatorRole_Operator <--o OperatorRole: operator_role_id

OperatorRole_Operator <--o Operator: operator_id

Operator <--o Client: client_id

right footer generated by sadisplay v0.3.2dev
@enduml