@startuml
Class Bank {
	id 		BigInteger
	code 		BigInteger
	name 		String


}

Class BankAccount {
	id 		BigInteger
	back_id 		BigInteger
	account_type 		Integer
	account_number 		String
	account_owner 		String
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		client

}

Class Client {
	id 		BigInteger
	contract_type 		Integer
	name 		String
	company_name 		String
	section_name 		String
	zip_code 		String
	country_code 		Integer
	prefecture_code 		Integer
	city 		String
	address 		String
	street 		String
	other_address 		String
	tel_1 		String
	tel_2 		String
	fax 		String
	bank_account_id 		BigInteger
	user_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		bank_account
	+		user
	+		event

}

Class Event {
	id 		BigInteger
	start_on 		Date
	end_on 		Date
	publish_at 		DateTime
	code 		String
	title 		String
	abbreviated_title 		String
	margin_ratio 		Float
	printing_fee 		Float
	registration_fee 		Float
	seats_and_prices 		String
	+		performances

}

Class MailPermission {
	id 		BigInteger
	email 		String
	user_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		user

}

Class Operator {
	id 		BigInteger
	name 		String
	email 		String
	client_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	login_id 		String
	secret_key 		String
	+		client
	+		OperatorRoll

}

Class OperatorActionHistory {
	id 		BigInteger
	function 		String
	data 		String
	created_at 		DateTime
	operator_id 		BigInteger
	+		operator

}

Class OperatorRoll {
	id 		BigInteger
	name 		String
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		operators
	+		permissions

}

Class Order {
	id 		BigInteger
	user_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		user
	+		items
	+		shipping_id
	+		order_item

}

Class OrderItem {
	id 		BigInteger
	order_id 		BigInteger
	product_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		order
	+		product

}

Class Performance {
	id 		BigInteger
	event_id 		BigInteger
	open_on 		DateTime
	start_on 		DateTime
	end_on 		DateTime
	no_period 		Boolean
	name 		String
	code 		String
	client_id 		BigInteger
	+		client
	+		event

}

Class Permission {
	id 		BigInteger
	operator_roll_id 		BigInteger
	category_code 		Integer
	permit 		Integer
	+		operator_roll

}

Class Product {
	id 		BigInteger
	name 		String
	price 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		items

}

Class ProductItem {
	id 		BigInteger
	price 		BigInteger
	item_type 		Integer
	performance_id 		BigInteger
	ticket_type_id 		BigInteger
	seat_type_id 		BigInteger
	product_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		performance
	+		ticket_type
	+		seat_type
	+		product

}

Class SeatStock {
	id 		BigInteger
	seat_id 		BigInteger
	venue_id 		BigInteger


}

Class SeatType {
	id 		BigInteger
	name 		String
	event_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		event

}

Class ShippingAddress {
	id 		BigInteger
	user_id 		BigInteger
	order_id 		BigInteger
	nick_name 		String
	first_name 		String
	last_name 		String
	first_name_kana 		String
	last_name_kana 		String
	birth_day 		DateTime
	sex 		Integer
	zip 		String
	prefecture 		String
	city 		String
	street 		String
	address 		String
	other_address 		String
	tel_1 		String
	tel_2 		String
	fax 		String
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		user
	+		order

}

Class TicketType {
	id 		BigInteger
	name 		String
	event_id 		BigInteger
	price 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		event

}

Class User {
	id 		BigInteger
	open_id_identifier 		String
	email 		String
	nick_name 		String
	first_name 		String
	last_name 		String
	first_name_kana 		String
	last_name_kana 		String
	birth_day 		DateTime
	sex 		Integer
	zip 		String
	prefecture 		String
	city 		String
	street 		String
	address 		String
	other_address 		String
	tel_1 		String
	tel_2 		String
	fax 		String
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		point_accounts
	+		user_point

}

Class UserPointAccount {
	id 		BigInteger
	user_id 		BigInteger
	point_type_code 		Integer
	account_number 		String
	account_expire 		String
	account_owner 		String
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		user

}

Class UserPointHistory {
	id 		BigInteger
	user_point_account_id 		BigInteger
	point 		Integer
	rate 		Integer
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer
	+		user_point_account

}

Class Event_DETAIL {
	id 		BigInteger
	seats_and_prices 		String


}

Class Event {
	id 		BigInteger
	start_on 		Date
	end_on 		Date
	publish_at 		DateTime
	code 		String
	title 		String
	abbreviated_title 		String
	margin_ratio 		Float
	printing_fee 		Float
	registration_fee 		Float


}

Class Operator_Auth {
	id 		BigInteger
	login_id 		String
	secret_key 		String


}

Class OperatorRoll_Operator {
	operator_roll_id 		BigInteger
	operator_id 		BigInteger


}

Class Operator {
	id 		BigInteger
	name 		String
	email 		String
	client_id 		BigInteger
	updated_at 		DateTime
	created_at 		DateTime
	status 		Integer


}

BankAccount <--o Bank: back_id

Client <--o BankAccount: bank_account_id

Client <--o User: user_id

MailPermission <--o User: user_id

Operator <--o Client: client_id

OperatorActionHistory <--o Operator: operator_id

Order <--o User: user_id

OrderItem <--o Order: order_id

OrderItem <--o Product: product_id

Performance <--o Event: event_id

Performance <--o Client: client_id

Permission <--o OperatorRoll: operator_roll_id

ProductItem <--o Performance: performance_id

ProductItem <--o TicketType: ticket_type_id

ProductItem <--o SeatType: seat_type_id

ProductItem <--o Product: product_id

SeatType <--o Event: event_id

ShippingAddress <--o User: user_id

ShippingAddress <--o Order: order_id

TicketType <--o Event: event_id

UserPointAccount <--o User: user_id

UserPointHistory <--o UserPointAccount: user_point_account_id

OperatorRoll_Operator <--o OperatorRoll: operator_roll_id

OperatorRoll_Operator <--o Operator: operator_id

Operator <--o Client: client_id

right footer generated by sadisplay v0.3.2dev
@enduml