"""autogenerate

Revision ID: 29cd1206e12f
Revises: None
Create Date: 2012-03-23 18:29:24.995072

"""

# revision identifiers, used by Alembic.
revision = '29cd1206e12f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'tag_page')
    op.drop_table(u'widget_summary')
    op.drop_table(u'widget_text')
    op.drop_table(u'widget_calendar')
    op.drop_table(u'topic')
    op.drop_table(u'tag')
    op.drop_table(u'mailmagazine_distribute')
    op.drop_table(u'image_asset')
    op.drop_table(u'mailmagazine_user')
    op.drop_table(u'widget_breadcrumbs')
    op.drop_table(u'layout')
    op.drop_table(u'widget_movie')
    op.drop_table(u'tag_asset')
    op.drop_table(u'tag_event')
    op.drop_table(u'asset')
    op.drop_table(u'order_history')
    op.drop_table(u'movie_asset')
    op.drop_table(u'widget')
    op.drop_table(u'mailmagazine')
    op.drop_table(u'flash_asset')
    op.drop_table(u'widget_performancelist')
    op.drop_table(u'widget_flash')
    op.drop_table(u'widget_ticketlist')
    op.drop_table(u'widget_menu')
    op.drop_table(u'user')
    op.drop_table(u'widget_topic')
    op.drop_table(u'widgetdisposition')
    op.drop_table(u'widget_image')
    op.drop_table(u'page')
    op.drop_table(u'widget_detail')
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table(u'tag_page',
    sa.Column(u'tag_id', sa.INTEGER(), nullable=False),
    sa.Column(u'page_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['page_id'], [u'page.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], [u'tag.id'], ),
    sa.PrimaryKeyConstraint(u'tag_id')
    )
    op.create_table(u'widget_summary',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'items', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'widget.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'widget_text',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'text', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'widget.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'widget_calendar',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'calendar_type', sa.VARCHAR(length=255), nullable=True),
    sa.Column(u'from_date', sa.DATE(), nullable=True),
    sa.Column(u'to_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'widget.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'topic',
    sa.Column(u'publish_open_on', sa.DATETIME(), nullable=True),
    sa.Column(u'publish_close_on', sa.DATETIME(), nullable=True),
    sa.Column(u'orderno', sa.INTEGER(), nullable=True),
    sa.Column(u'is_vetoed', sa.BOOLEAN(), nullable=True),
    sa.Column(u'is_global', sa.BOOLEAN(), nullable=True),
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'created_at', sa.DATETIME(), nullable=True),
    sa.Column(u'updated_at', sa.DATETIME(), nullable=True),
    sa.Column(u'client_id', sa.INTEGER(), nullable=True),
    sa.Column(u'site_id', sa.INTEGER(), nullable=True),
    sa.Column(u'kind', sa.VARCHAR(length=255), nullable=True),
    sa.Column(u'title', sa.VARCHAR(), nullable=True),
    sa.Column(u'text', sa.VARCHAR(), nullable=True),
    sa.Column(u'event_id', sa.INTEGER(), nullable=True),
    sa.Column(u'page_id', sa.INTEGER(), nullable=True),
    sa.CheckConstraint('TODO'),
    sa.CheckConstraint('TODO'),
    sa.ForeignKeyConstraint(['client_id'], [u'client.id'], ),
    sa.ForeignKeyConstraint(['event_id'], [u'event.id'], ),
    sa.ForeignKeyConstraint(['page_id'], [u'page.id'], ),
    sa.ForeignKeyConstraint(['site_id'], [u'site.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'tag',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'name', sa.VARCHAR(), nullable=True),
    sa.Column(u'is_public', sa.INTEGER(), nullable=True),
    sa.Column(u'site_id', sa.INTEGER(), nullable=True),
    sa.Column(u'type', sa.VARCHAR(), nullable=True),
    sa.Column(u'created_at', sa.DATETIME(), nullable=True),
    sa.Column(u'updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], [u'site.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'mailmagazine_distribute',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'mailmagazine_id', sa.INTEGER(), nullable=True),
    sa.Column(u'username', sa.VARCHAR(), nullable=True),
    sa.Column(u'email', sa.VARCHAR(), nullable=True),
    sa.Column(u'status', sa.VARCHAR(), nullable=True),
    sa.Column(u'send_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['mailmagazine_id'], [u'mailmagazine.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'image_asset',
    sa.Column(u'alt', sa.INTEGER(), nullable=True),
    sa.Column(u'size', sa.INTEGER(), nullable=True),
    sa.Column(u'width', sa.INTEGER(), nullable=True),
    sa.Column(u'height', sa.INTEGER(), nullable=True),
    sa.Column(u'filepath', sa.VARCHAR(), nullable=True),
    sa.Column(u'mimetype', sa.VARCHAR(), nullable=True),
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], [u'asset.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'mailmagazine_user',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'mailmagazine_id', sa.INTEGER(), nullable=True),
    sa.Column(u'user_id', sa.INTEGER(), nullable=True),
    sa.Column(u'joined_at', sa.DATETIME(), nullable=True),
    sa.Column(u'can_distribute', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['mailmagazine_id'], [u'mailmagazine.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'widget_breadcrumbs',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], [u'widget.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'layout',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'created_at', sa.DATETIME(), nullable=True),
    sa.Column(u'updated_at', sa.DATETIME(), nullable=True),
    sa.Column(u'title', sa.VARCHAR(), nullable=True),
    sa.Column(u'template_filename', sa.VARCHAR(), nullable=True),
    sa.Column(u'blocks', sa.VARCHAR(), nullable=True),
    sa.Column(u'site_id', sa.INTEGER(), nullable=True),
    sa.Column(u'client_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], [u'client.id'], ),
    sa.ForeignKeyConstraint(['site_id'], [u'site.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'widget_movie',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'asset_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], [u'asset.id'], ),
    sa.ForeignKeyConstraint(['id'], [u'widget.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'tag_asset',
    sa.Column(u'tag_id', sa.INTEGER(), nullable=False),
    sa.Column(u'asset_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], [u'asset.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], [u'tag.id'], ),
    sa.PrimaryKeyConstraint(u'tag_id')
    )
    op.create_table(u'tag_event',
    sa.Column(u'tag_id', sa.INTEGER(), nullable=False),
    sa.Column(u'event_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], [u'event.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], [u'tag.id'], ),
    sa.PrimaryKeyConstraint(u'tag_id')
    )
    op.create_table(u'asset',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'type', sa.VARCHAR(length=32), nullable=False),
    sa.Column(u'created_at', sa.DATETIME(), nullable=True),
    sa.Column(u'updated_at', sa.DATETIME(), nullable=True),
    sa.Column(u'site_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], [u'site.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'order_history',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'created_at', sa.DATETIME(), nullable=True),
    sa.Column(u'updated_at', sa.DATETIME(), nullable=True),
    sa.Column(u'ticket_id', sa.INTEGER(), nullable=True),
    sa.Column(u'user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], [u'ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'movie_asset',
    sa.Column(u'alt', sa.INTEGER(), nullable=True),
    sa.Column(u'size', sa.INTEGER(), nullable=True),
    sa.Column(u'width', sa.INTEGER(), nullable=True),
    sa.Column(u'height', sa.INTEGER(), nullable=True),
    sa.Column(u'filepath', sa.VARCHAR(), nullable=True),
    sa.Column(u'mimetype', sa.VARCHAR(), nullable=True),
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'imagepath', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'asset.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'widget',
    sa.Column(u'page_id', sa.INTEGER(), nullable=True),
    sa.Column(u'disposition_id', sa.INTEGER(), nullable=True),
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'site_id', sa.INTEGER(), nullable=True),
    sa.Column(u'type', sa.VARCHAR(length=32), nullable=False),
    sa.Column(u'created_at', sa.DATETIME(), nullable=True),
    sa.Column(u'updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['disposition_id'], [u'widgetdisposition.id'], ),
    sa.ForeignKeyConstraint(['page_id'], [u'page.id'], ),
    sa.ForeignKeyConstraint(['site_id'], [u'site.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'mailmagazine',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'title', sa.VARCHAR(), nullable=True),
    sa.Column(u'description', sa.VARCHAR(), nullable=True),
    sa.Column(u'site_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], [u'site.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'flash_asset',
    sa.Column(u'alt', sa.INTEGER(), nullable=True),
    sa.Column(u'size', sa.INTEGER(), nullable=True),
    sa.Column(u'width', sa.INTEGER(), nullable=True),
    sa.Column(u'height', sa.INTEGER(), nullable=True),
    sa.Column(u'filepath', sa.VARCHAR(), nullable=True),
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'mimetype', sa.VARCHAR(), nullable=True),
    sa.Column(u'imagepath', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'asset.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'widget_performancelist',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], [u'widget.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'widget_flash',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'asset_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], [u'asset.id'], ),
    sa.ForeignKeyConstraint(['id'], [u'widget.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'widget_ticketlist',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['id'], [u'widget.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'widget_menu',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'items', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'widget.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'user',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'created_at', sa.DATETIME(), nullable=True),
    sa.Column(u'updated_at', sa.DATETIME(), nullable=True),
    sa.Column(u'email', sa.VARCHAR(), nullable=True),
    sa.Column(u'site_id', sa.INTEGER(), nullable=True),
    sa.Column(u'is_active', sa.INTEGER(), nullable=True),
    sa.Column(u'is_administrator', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], [u'site.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'widget_topic',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'display_count', sa.INTEGER(), nullable=True),
    sa.Column(u'display_global', sa.BOOLEAN(), nullable=True),
    sa.Column(u'display_event', sa.BOOLEAN(), nullable=True),
    sa.Column(u'display_page', sa.BOOLEAN(), nullable=True),
    sa.Column(u'kind', sa.VARCHAR(length=255), nullable=True),
    sa.CheckConstraint('TODO'),
    sa.CheckConstraint('TODO'),
    sa.CheckConstraint('TODO'),
    sa.ForeignKeyConstraint(['id'], [u'widget.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'widgetdisposition',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'title', sa.VARCHAR(length=255), nullable=True),
    sa.Column(u'site_id', sa.INTEGER(), nullable=True),
    sa.Column(u'structure', sa.VARCHAR(), nullable=True),
    sa.Column(u'blocks', sa.VARCHAR(), nullable=True),
    sa.Column(u'is_public', sa.BOOLEAN(), nullable=True),
    sa.Column(u'owner_id', sa.INTEGER(), nullable=True),
    sa.Column(u'created_at', sa.DATETIME(), nullable=True),
    sa.Column(u'updated_at', sa.DATETIME(), nullable=True),
    sa.CheckConstraint('TODO'),
    sa.ForeignKeyConstraint(['owner_id'], [u'operator.id'], ),
    sa.ForeignKeyConstraint(['site_id'], [u'site.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'widget_image',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'asset_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], [u'asset.id'], ),
    sa.ForeignKeyConstraint(['id'], [u'widget.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'page',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'parent_id', sa.INTEGER(), nullable=True),
    sa.Column(u'event_id', sa.INTEGER(), nullable=True),
    sa.Column(u'created_at', sa.DATETIME(), nullable=True),
    sa.Column(u'updated_at', sa.DATETIME(), nullable=True),
    sa.Column(u'title', sa.VARCHAR(), nullable=True),
    sa.Column(u'keywords', sa.VARCHAR(), nullable=True),
    sa.Column(u'description', sa.VARCHAR(), nullable=True),
    sa.Column(u'url', sa.VARCHAR(), nullable=True),
    sa.Column(u'version', sa.INTEGER(), nullable=True),
    sa.Column(u'site_id', sa.INTEGER(), nullable=True),
    sa.Column(u'layout_id', sa.INTEGER(), nullable=True),
    sa.Column(u'structure', sa.VARCHAR(), nullable=True),
    sa.Column(u'hash_url', sa.VARCHAR(length=32), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], [u'event.id'], ),
    sa.ForeignKeyConstraint(['layout_id'], [u'layout.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], [u'page.id'], ),
    sa.ForeignKeyConstraint(['site_id'], [u'site.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    op.create_table(u'widget_detail',
    sa.Column(u'id', sa.INTEGER(), nullable=False),
    sa.Column(u'kind', sa.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], [u'widget.id'], ),
    sa.PrimaryKeyConstraint(u'id')
    )
    ### end Alembic commands ###
