"""asset auth event layuout page tag topcontent topic usersetting widget

Revision ID: 44c6064e1b5f
Revises: 34b7cbb33f85
Create Date: 2012-04-16 11:45:59.043315

"""

# revision identifiers, used by Alembic.
revision = '44c6064e1b5f'
down_revision = '34b7cbb33f85'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assettag2asset',
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['assettag.id'], ),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('eventtag2event',
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['eventtag.id'], ),
    sa.PrimaryKeyConstraint('tag_id')
    )
    op.create_table('widget',
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('disposition_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disposition_id'], ['widgetdisposition.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('layout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('template_filename', sa.String(), nullable=True),
    sa.Column('blocks', sa.String(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailmagazine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flash_asset',
    sa.Column('alt', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mimetype', sa.String(), nullable=True),
    sa.Column('imagepath', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widgetdisposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Unicode(length=255), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('structure', sa.String(), nullable=True),
    sa.Column('blocks', sa.String(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['operator.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topcontent',
    sa.Column('publish_open_on', sa.DateTime(), nullable=True),
    sa.Column('publish_close_on', sa.DateTime(), nullable=True),
    sa.Column('orderno', sa.Integer(), nullable=True),
    sa.Column('is_vetoed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Unicode(length=255), nullable=True),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('text', sa.Unicode(), nullable=True),
    sa.Column('image_asset_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('countdown_type', sa.String(length=255), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),

    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['image_asset_id'], ['image_asset.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('keywords', sa.Unicode(), nullable=True),
    sa.Column('description', sa.Unicode(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('layout_id', sa.Integer(), nullable=True),
    sa.Column('structure', sa.String(), nullable=True),
    sa.Column('hash_url', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['layout_id'], ['layout.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('topic',
    sa.Column('publish_open_on', sa.DateTime(), nullable=True),
    sa.Column('publish_close_on', sa.DateTime(), nullable=True),
    sa.Column('orderno', sa.Integer(), nullable=True),
    sa.Column('is_vetoed', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Unicode(length=255), nullable=True),
    sa.Column('title', sa.Unicode(), nullable=True),
    sa.Column('text', sa.Unicode(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('page_id', sa.Integer(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assettag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Unicode(length=255), nullable=True),
    sa.Column('publicp', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagetag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Unicode(length=255), nullable=True),
    sa.Column('publicp', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventtag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Unicode(length=255), nullable=True),
    sa.Column('publicp', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['ticket.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagetag2page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['object_id'], ['page.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['pagetag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movie_asset',
    sa.Column('alt', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('mimetype', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imagepath', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailmagazine_distribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailmagazine_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.Unicode(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('send_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mailmagazine_id'], ['mailmagazine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('image_asset',
    sa.Column('alt', sa.Integer(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('filepath', sa.String(), nullable=True),
    sa.Column('mimetype', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mailmagazine_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mailmagazine_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('can_distribute', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mailmagazine_id'], ['mailmagazine.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('site_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Integer(), nullable=True),
    sa.Column('is_administrator', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assettag2asset')
    op.drop_table('eventtag2event')
    op.drop_table('widget')
    op.drop_table('layout')
    op.drop_table('mailmagazine')
    op.drop_table('flash_asset')
    op.drop_table('widgetdisposition')
    op.drop_table('topcontent')
    op.drop_table('page')
    op.drop_table('topic')
    op.drop_table('assettag')
    op.drop_table('pagetag')
    op.drop_table('asset')
    op.drop_table('eventtag')
    op.drop_table('order_history')
    op.drop_table('pagetag2page')
    op.drop_table('movie_asset')
    op.drop_table('mailmagazine_distribute')
    op.drop_table('image_asset')
    op.drop_table('mailmagazine_user')
    op.drop_table('user')
    ### end Alembic commands ###
