"""widget plugins

Revision ID: 55e85c67382
Revises: 44c6064e1b5f
Create Date: 2012-04-16 11:51:51.540940

"""

# revision identifiers, used by Alembic.
revision = '55e85c67382'
down_revision = '44c6064e1b5f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('widget_breadcrumbs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('items', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Unicode(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('href', sa.String(), nullable=True),
    sa.Column('alt', sa.Unicode(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('nowrap', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_reuse',
    sa.Column('attrs', sa.String(), nullable=True),
    sa.Column('source_page_id', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.ForeignKeyConstraint(['source_page_id'], ['page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_performancelist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_flash',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_type', sa.String(length=255), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('items', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_countdown',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_ticketlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_topic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic_type', sa.String(length=255), nullable=True),
    sa.Column('display_count', sa.Integer(), nullable=True),
    sa.Column('display_global', sa.Boolean(), nullable=True),
    sa.Column('display_event', sa.Boolean(), nullable=True),
    sa.Column('display_page', sa.Boolean(), nullable=True),
    sa.Column('kind', sa.Unicode(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('widget_movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset.id'], ),
    sa.ForeignKeyConstraint(['id'], ['widget.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###

def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('widget_breadcrumbs')
    op.drop_table('widget_summary')
    op.drop_table('widget_text')
    op.drop_table('widget_image')
    op.drop_table('widget_reuse')
    op.drop_table('widget_performancelist')
    op.drop_table('widget_flash')
    op.drop_table('widget_calendar')
    op.drop_table('widget_menu')
    op.drop_table('widget_countdown')
    op.drop_table('widget_ticketlist')
    op.drop_table('widget_detail')
    op.drop_table('widget_topic')
    op.drop_table('widget_movie')
    ### end Alembic commands ###
