  <div class="footer">
	  
        <div class="footernav">
          <ul>
            <li class="first"><a href="/static/faq/faq.html">ヘルプ</a></li>
            <li><a href="http://www.ticketstar.jp/corporate">運営会社</a></li>
            <li><a href="https://ticket.rakuten.co.jp/contact/form">お問い合わせ</a></li>
            <li><a href="http://www.ticketstar.jp/privacy">個人情報保護方針</a></li>
            <li class="last"><a href="http://www.ticketstar.jp/legal">特定商取引法に基づく表示</a></li>
          </ul>
        </div>
        <div class="copyright">
          Copyright &copy; 2010-2012 TicketStar Inc. All Rights Reserved. 
        </div>

  </div>
